### PR TITLE
ZIO1 CE2: Update zio to 1.0.18

### PR DESCRIPTION
**Pull request by neko-kai**

### CODE REVIEW

**Comment by tellnobody1** [comment]
Maybe it worth to update scala to 2.12.17 and 2.13.10 to fix evicted warnings.

**Comment by tellnobody1** [comment]
@neko-kai are you still working on this PR?

**Comment by neko-kai** [comment]
> @neko-kai are you still working on this PR?

Yes.

**Comment by tellnobody1** [comment]
You just need to fix:
```diff
- case Some((3, 0)) =>
+ case Some((3, _)) =>
```
for `extraOptions` in `BuilderHelper.scala:55'.

**Comment by neko-kai** [comment]
@tellnobody1 
Thanks for noticing that! Although what's holding this update back are weird Scala3+Scala.js errors that I can't understand the cause of:
```
[info] Fast optimizing /home/runner/work/interop-cats/interop-cats/zio-interop-cats-tests/js/target/scala-3.2.2/zio-interop-cats-tests-test-fastopt
[error] Referring to non-existent method zio.test.Assertion.apply(java.lang.Object)java.lang.Object
[error]   called from scala.collection.mutable.Builder$$anon$1.result()java.lang.Object
[error]   called from constructor izumi.reflect.thirdparty.internal.boopickle.IdentListBig.<init>(izumi.reflect.thirdparty.internal.boopickle.IdentList$Entry,int)void
[error]   called from izumi.reflect.thirdparty.internal.boopickle.IdentList1Plus.updated(java.lang.Object)izumi.reflect.thirdparty.internal.boopickle.IdentList
[error]   called from izumi.reflect.thirdparty.internal.boopickle.UnpickleState.addIdentityRef(java.lang.Object)void
[error]   called from izumi.reflect.macrortti.LightTypeTag$$anon$23.unpickle(izumi.reflect.thirdparty.internal.boopickle.UnpickleState)izumi.reflect.macrortti.LightTypeTag$ParsedLightTypeTag$SubtypeDBs
[error]   called from izumi.reflect.macrortti.LightTypeTag$$anon$23.unpickle(izumi.reflect.thirdparty.internal.boopickle.UnpickleState)java.lang.Object
[error]   called from private izumi.reflect.macrortti.LightTypeTag$.shared$lzyINIT1$1(java.lang.String,scala.runtime.LazyRef)izumi.reflect.macrortti.LightTypeTag$ParsedLightTypeTag$SubtypeDBs
[error]   called from private izumi.reflect.macrortti.LightTypeTag$.shared$1(java.lang.String,scala.runtime.LazyRef)izumi.reflect.macrortti.LightTypeTag$ParsedLightTypeTag$SubtypeDBs
[error]   called from private izumi.reflect.macrortti.LightTypeTag$.parse$$anonfun$2(java.lang.String,scala.runtime.LazyRef)scala.collection.immutable.Map
[error]   called from izumi.reflect.macrortti.LightTypeTag$.parse(int,java.lang.String,java.lang.String,int)izumi.reflect.macrortti.LightTypeTag
[error]   called from constructor zio.test.DefaultMutableRunnableSpec.<init>()void
[error]   called from static constructor zio.test.DefaultMutableRunnableSpec.<stinit>()void
[error]   called from core module analyzer
[error] involving instantiated classes:
[error]   scala.collection.mutable.Builder$$anon$1
[error]   izumi.reflect.thirdparty.internal.boopickle.IdentList1Plus
[error]   izumi.reflect.thirdparty.internal.boopickle.UnpickleState
[error]   izumi.reflect.macrortti.LightTypeTag$$anon$23
[error]   izumi.reflect.macrortti.LightTypeTag$
```
https://github.com/zio/interop-cats/actions/runs/4107563325/jobs/7087204112

**Comment by tellnobody1** [comment]
I have similar problem with `zio-logging`. So, there are a problem in `ci.yml`:
* Line 48 and 51 are checking for `3.0.0`
* When Scala 3 is used you need to drop `!` when switching a version. The example is https://github.com/zio/zio-logging/blob/series/1.x/.github/workflows/ci.yml#L64. Otherwise, there should be conflict of `_2.13` and `_3` suffixes.

For some reason `interop-cats` and `zio-logging` weren't running ScalaJS tests. There is no problem to run them though.

**Comment by neko-kai** [comment]
@tellnobody1 
I've checked zio-logging and it actually still suffers from this error with `zio.test.Assertion.apply` on Scala 3+Scala.js. The reason it works for you when ommitting `!` from `++` is because that causes build to _skip_ testing for coreJS - which does not use `dottySettings` in build, so it isn't set to build for Scala.js in its `crossScalaSettings`:
```
sbt:zio-logging> crossScalaVersions
[info] slf4j / crossScalaVersions
[info]  List(2.11.12, 2.12.17, 2.13.10, 3.2.2)
[info] coreJS / crossScalaVersions
[info]  List(2.11.12, 2.12.17, 2.13.10)
[info] slf4jBridge / crossScalaVersions
[info]  List(2.11.12, 2.12.17, 2.13.10, 3.2.2)
[info] examples / crossScalaVersions
[info]  List(2.11.12, 2.12.17, 2.13.10, 3.2.2)
[info] jsconsole / crossScalaVersions
[info]  List(2.11.12, 2.12.17, 2.13.10)
[info] jshttp / crossScalaVersions
[info]  List(2.11.12, 2.12.17, 2.13.10)
[info] benchmarks / crossScalaVersions
[info]  List(2.11.12, 2.12.17, 2.13.10)
[info] coreJVM / crossScalaVersions
[info]  List(2.11.12, 2.12.17, 2.13.10, 3.2.2)
[info] docs / crossScalaVersions
[info]  List(2.13.10)
[info] crossScalaVersions
[info]  List(2.13.10)
```

This error seems to be caused just by updating from zio 1.0.17 to 1.0.18 - as if the SJS bytecode itself is incorrect, don't know what could make it incorrect - other than a regression in dotty. Between 1.0.17 and 1.0.18 dotty was updated from 3.1.2 to 3.2.1. I tried publishing zio & izumi-reflect with 3.1.3 and 3.3.0-RC3 versions, but the error persisted. Scala.js was also updated, but downgrading it to 1.10.0 didn't fix the issue. Testing publishing with 3.1.2 requires changes in izumi-reflect since it uses functions that appeared in 3.1.3 - but it's possible that's the point when the regression happened, I've yet to test that.

**Comment by neko-kai** [comment]
Yes, the cause is just Scala 3 `3.1.3` (and all later versions), it's enough to check out tag zio/zio tag `v1.0.17`, change Scala3 version to 3.1.3, publish locally and use it in interop-cats to reproduce the issue.

**Comment by tellnobody1** [comment]
@neko-kai could you then ignore ScalaJS tests (as was before) for Scala 3 to unblock release? Because it is critical update of ZIO which blocks usage of ZIO1 CE2 with Scala 3.

Or, as an option, to switch Scala 3 version to 3.1.2. It shouldn't be a problem for projects which will use 3.2.2.

**Comment by neko-kai** [comment]
@tellnobody1 
> could you then ignore ScalaJS tests (as was before) for Scala 3 to unblock release? Because it is critical update of ZIO which blocks usage of ZIO1 CE2 with Scala 3.

Ok, I'll go ahead and release as-is.

> Or, as an option, to switch Scala 3 version to 3.1.2. It shouldn't be a problem for projects which will use 3.2.2.

izumi-reflect uses dotty reflection functions that appeared in 3.1.3 so it's impossible to compile anything that uses it on <3.1.3, so that's not an option sadly.

**Pull request merged**
