### PR TITLE
Upgrade ZIO Version

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Review by calvinlfer — APPROVED** [review]

**Comment by neko-kai** [comment]
Was `ZIO#raceWith` deleted?

**Comment by adamgfraser** [comment]
`ZIO.raceWith` is implemented in terms of `ZIO.raceFibersWith` which forks the child fibers in the parent scope and is inconsistent with Cats Effect semantic. So we implement our own version of `raceFibersWith` that does not do this and implement our own version of `raceWith` in terms of that.

**Comment by vigoo** [comment]
Maybe it would worth marking the difference with a comment, I was looking at the two for minutes and did not see it :D

**Comment by adamgfraser** [comment]
Added a comment.

**Review by neko-kai — APPROVED** [review]

**Pull request merged**
