### PR TITLE
Update to latest zio

### PR DESCRIPTION
**Pull request by ioleo**
I'm experimenting with new DI encoding (Has & ZLayer) from the latest ZIO and I needed to update interop-cats to play with http4s/doobie.
This ofcourse will need to be updated when the next version lands (be it `1.0.0` or `1.0.0-RC18`).

### CODE REVIEW

**Comment by ioleo** [comment]
@pierangeloc After all day playing around I come to discord to discover you did the same work today :joy:

**Comment by pierangeloc** [comment]
@ioleo my branch https://github.com/pierangeloc/interop-cats/tree/use-zio-rc18-snapshot
 works for 2.13 (including tests) but fails for other Scala versions. I managed to `publishLocal` and use it with http4s (no doobie yet though).
I am also writing some documentation on the new ZLayer approach, to eventually contribute it to ZIO website. Just to avoid double work :-), are you busy doing the same?

**Comment by mijicd** [comment]
I don't think we should depend on snapshots. It's super convenient for development for sure, but it feels a bit odd to have it here.

**Comment by ghostdogpr** [comment]
@mijicd I think it's good to have that PR ready although we don't merge it until the actual RC is released. Several times in the past we released zio and everybody was expecting interop-cats to follow but there was substantial work to do. It's much better if that work is done beforehand.

**Comment by mijicd** [comment]
@ghostdogpr with this I agree 100% :)

**Comment by ioleo** [comment]
@pierangeloc I'm playing around for myself, but a thought to create some docs/blog post/whatever crossed my mind. I'm quite busy lately so it might take a while, by that time I will first check if you had not posted something already :)

**Pull request closed without merging**
