### PR TITLE
Upgrade ZIO Interop Cats Effect 2 to ZIO 2.0.0-RC1

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Finding myself in the need for this to upgrade Caliban to ZIO 2.0 (because of monix interop, since monix still depends on CE 2.0).

**Comment by adamgfraser** [comment]
@ghostdogpr Will do this today.

**Comment by adamgfraser** [comment]
This is ready now. We need a fix for an early initialization issue that was made in ZIO after RC1 for the tests.

**Comment by adamgfraser** [comment]
Superseded by #495.

**Pull request closed without merging**
